name: CI + CD

on:
  schedule:
    - cron: 0 12 * * 6
  workflow_dispatch:
    inputs:
      lighthouse:
        description: Scan web with lighthouse
        required: false
        default: true     
        type: boolean

env:
  REPOSITORY: eddiesigner/liebling
  DOMAIN: https://blog.danieljsaldaña.com        

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    secrets:
      GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
      GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}

  scan:
    name: Check action
    needs: [deploy]
    uses: ./.github/workflows/lighthouse.yml