name: Theme Ghost

on:
  workflow_call:

jobs:
  theme-ghost:
    steps:
      - name: ☁️ checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.events.inputs.repository }}