name: Theme Ghost

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository name with'
        required: true
        default: ''  

jobs:
  theme-ghost:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.events.inputs.repository }}