name: Theme Ghost

on:
  workflow_call:

jobs:
  theme-ghost:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}