name: Deploy Theme

on:
  schedule:
    - cron: '0 12 * * 6'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name with'
        required: true
        default: 'eddiesigner/liebling'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ checkout repository
        uses: actions/checkout@v3
        with:
          repository: eddiesigner/liebling

      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}